## Run the perl solution:
# define RUN
# 	./solution.pl < $(2)
# endef

## Run the lua solution:
# define RUN
# 	lua solution.lua < $(2)
# endef

## Run the factor solution:
define RUN
	/Applications/factor/Factor.app/Contents/MacOS/factor solution.factor < $(2)
endef

include ../common.mk
